import { IsNotEmpty, IsNumber, IsString } from 'class-validator';

export class CastVoteDto {
    @IsNumber()
    @IsNotEmpty()
    pollId: number;

    @IsNumber()
    @IsNotEmpty()
    optionIndex: number;

    @IsString()
    @IsNotEmpty()
    nullifier: string; // The cryptographic identity nullifier token generated by the citizen
}